# [ARE 212] Discussion Section - Python 02


- [Ethan's materials](https://github.com/ligonteaching/ARE212_Materials)
- [My github](https://github.com/bk-econ/share)

### Source Material

These notes are the fruits of arduous labor of others.  My contributions are minimual, but please expect to find some code (and even explanation) errors (and assume them all to be mine). If you find any mistakes or have questions, please [let me know](mailto:benjaminkrause@berkeley.edu).
    
The primary sources of these notes are:
- Ethan and in particular his EEP 153 Notes
- [Computational and Inferential Thinking: The Foundations of Data Science](https://www.inferentialthinking.com/chapters/intro.html) which is the textbook for UC Berkeley's [Data 8: The Foundations of Data Science](http://data8.org/) course.  All of the notes, readings, labs, and assignments are fully available online as well.  For instance, here is [Spring 2020](http://data8.org/sp20/).
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)

### Follow-up from questions posed last week

- Discussions: See [Ethan's full response](https://bcourses.berkeley.edu/courses/1487913/discussion_topics/5737368)
    - *When is discussion participation "due"?*  
        - Initial response by Wednesday
        - Further contributiioins can be later in the week (including over the weekend)
- Final format: See [Ethan's full response](https://bcourses.berkeley.edu/courses/1487913/discussion_topics/5737448) 
    - *Do we need to be able to code in Python?* 
        - "My intention, rather, is to provide you with some simple working notebooks you can play with, and follow along with to achieve instructional ends which aren't principally focused on on new language acquisition"
        - "I'll make sure the final doesn't require python mastery."
    - *What should we expect in the final?* 
        - "My intention is for the topics raised in the discussions to serve as likely jumping off points for the final. 
        - ". . . students are responsible for the content of the lecture, and should be familiar with the specific readings I reference (not necessarily all the papers mentioned in the syllabus)."

## Review Lecture Jupyter Notebooks 1

### Learning Goals Today

1.  Review [classical_regression](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Materials/classical_regression.ipynb)
2.  Review [weighted_regression](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Materials/weighted_regression.ipynb) 
  

NB: If needed, review the introduction from last week at [ARE 212 Discussion Section - Python 01](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Discussion_Section/%5BARE%20212%5D%20Discussion%20Section%20-%20Python%2001.ipynb) or from [my github](https://github.com/bk-econ/share).

##### Open a `jupyter` notebook on `datahub.berkeley.edu`

1. Open the website [URL to Interact](https://url-to-interact.herokuapp.com/)
2. For `1. Choose your desired hub:` select `datahub.berkeley.edu`
3. Either navigate to [my github](https://github.com/bk-econ/share) page and select the `URL` of the correct section or simply copy it from right here: https://github.com/bk-econ/share/blob/master/%5BARE%20212%5D%20Discussion%20Section%20-%20Python%2001.ipynb
4. Paste the `URL` you copied in the previous step into `2. Paste the GitHub URL for your file or folder in the box below.`
5. Click `Convert to interact link!`
6. Copy the new `URL` generated in field `4. Your interact link URL will appear in the box below.`
7. Paste the new `URL` in any web browser and get to it!

### 1. [classical_regression](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Materials/classical_regression.ipynb)

or see [classical regression on github](https://github.com/ligonteaching/ARE212_Materials/blob/master/classical_regression.ipynb)

#### Classical regression in =python=



The fact that $X$ and $u$ are &ldquo;independent&rdquo; variables means that
if we want to compute a &ldquo;classical&rdquo; regression we&rsquo;d do it
something like this:



##### Define independent random variables

In [42]:
# 1.1. ORIGINAL CODE
%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal

k = 2 # Number of observables

mu = [0]*k
Sigma=[[1,0.5],
       [0.5,2]]

X = multivariate_normal(mu,Sigma)

u = multivariate_normal(cov=0.2)

<font color='red'> *notes*: </font>
- `%matplotlib inline`
    - `%` is used to call [magic functions](https://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained) in `Python`.
    - [`matplotlib`](https://matplotlib.org/) - "comprehensive library for creating static, animated, and interactive visualizations in Python"
        - Here is a more comprehensive treatment of [Using matplotlib in jupyter notebooks](https://medium.com/@1522933668924/using-matplotlib-in-jupyter-notebooks-comparing-methods-and-some-tips-python-c38e85b40ba1)
        - Originally designed to enable MATLAB-style plotting via gnuplot from the [IPython](https://plotly.com/python/ipython-vs-python/) command line
        - Noteable because it plays well with many operating systems and graphics packages
    - `inline` simply means that any plots we create are going to appear in our notebook inline 


In [31]:
# check the available backends for matplotlib with --list
%matplotlib --list

Available matplotlib backends: ['tk', 'gtk', 'gtk3', 'wx', 'qt4', 'qt5', 'qt', 'osx', 'nbagg', 'notebook', 'agg', 'svg', 'pdf', 'ps', 'inline', 'ipympl', 'widget']


<font color='red'> *notes*: </font>
- `import numpy as np` 
    - [numpy](https://numpy.org/): mathematical functions, generally used to create arrays
- `from scipy.stats import multivariate_normal`
    - `import X` vs `from X import x` (Explanation from this [Stack Exchange](https://stackoverflow.com/questions/9439480/from-import-vs-import))
        - `import X`: "Imports the module X, and creates a reference to that module in the current namespace. Then you need to define completed module path to access a particular attribute or method from inside the module (e.g.: X.name or X.attribute)"
        - `from X import x`: "Imports the module X, and creates references to all public objects defined by that module in the current namespace . . . after you've run this statement, you can simply use a plain (unqualified) name to refer to things defined in module X." 
            - "But X itself is not defined, so X.name doesn't work."
            - "And if name was already defined, it is replaced by the new version." 
            - "And if name in X is changed to point to some other object, your module won’t notice."
    - `scipy.stats`
        - [scipy](https://www.scipy.org/): scientific functions
        - `scipy.stats` is the set of statistical functions within `scipy`

In [32]:
import scipy
# scipy?
#  A scientific computing package for Python . . . 
## imports all the functions from the NumPy namespace, and in addition provides:
## Subpackages: Using any of these subpackages requires an explicit import.  
## For example,``import scipy.cluster``.

In [5]:
# scipy.stats?
# This module contains a large number of probability distributions 
## as well as a growing library of statistical functions.

In [33]:
# scipy.stats.multivariate_normal?
# A multivariate normal random variable.
### multivariate_normal(mean=None,
                    ### cov=1,
                    ### allow_singular=False,
                    ### seed=None,
                    ### )

In [47]:
# 1.1. CODE ABOVE WITH COMMENTS AND PRINTING

# run magic function matplotlib to have visualizations inline in your notebook
%matplotlib inline 

# import the NumPy module and call it "np"
import numpy as np # see notes below

# import just the multivariate_normal function from the "stats" functions of the SciPy module
from scipy.stats import multivariate_normal 

# k gets 2
k = 2 # Number of observables; R::k <- 2
print("k =", k)

# mu gets the 1x2 zero vector
mu = [0]*k
print("mu =", mu)

# sigma gets the following matrix (note the use double brackets)
Sigma=[[1,0.5],
       [0.5,2]] # R::matrix(c(1, .5, .5, 2), nrow=2, byrow=TRUE)
print("Sigma =", Sigma)

# X gets a multivariate normal random variable with mean = mu and cov = Sigma 
X = multivariate_normal(mu,Sigma) 
print("X =", X)

# u gets a multivariate normal random variable with mean = 0 and cov = .2 
u = multivariate_normal(cov=0.2) # 
print("u =", u)

NameError: name 'setseed' is not defined

##### Construct Sample



To construct a sample of observables $(y,X)$ we just use the regression equation,
     plus an assumption about the value of $\beta$:



In [44]:
# 1.2. ORIGINAL CODE

beta = [1/2,1]

N=1000 # Sample size

# Now: Transform r.v. X into a sample
Xrvs = X.rvs(N)

y = Xrvs@beta + u.rvs(N) # Note use of @ operator for matrix multiplication

<font color='red'> *notes*: </font>
- `X.rvs(size = n)` yields a random sample of size n from the object X 
- `@` represents matrix multiplication (as already stated above); R::%*%

In [45]:
# 1.2. CODE ABOVE WITH COMMENTS AND PRINTING

# beta gets a list of 1/2 and 1
beta = [1/2,1] # R::list(1/2, 1)
print("beta =", beta)

# N gets 1000
N=1000 # Sample size
print("N =", N)

# Now: Transform random variable X into a sample of N draws
X = X.rvs(N)
print("X =", X)

# y gets (R::X %*% beta + U)  where U is a sample of N draws from u
y = X@beta + u.rvs(N) # Note use of @ operator for matrix multiplication
print("y =", y)

beta = [0.5, 1]
N = 1000
X = [[ 1.83060078e+00  3.29108751e+00]
 [-3.73065819e-01  1.81987481e+00]
 [ 2.60583681e-03 -6.95979686e-02]
 ...
 [ 9.18830004e-01 -1.47532613e-01]
 [ 4.43816010e-01 -1.63953599e+00]
 [ 7.72931540e-01  3.25456680e-01]]
y = [ 4.15323223e+00  1.57593293e+00 -8.92900708e-01  3.63055938e+00
 -9.42805732e-01  1.25090666e+00  1.33234155e+00 -3.44921295e-01
  6.14277188e-01  1.06841910e-01 -1.16316395e-01  3.99417847e+00
 -9.54343171e-01  1.44271715e+00 -2.16166953e+00 -3.70770738e-01
 -9.22714305e-01  3.02260156e+00  1.10104795e+00  3.55070482e-01
 -3.08398704e+00 -5.84769127e-01  1.57342201e+00 -6.87316112e-01
 -8.56972052e-02 -3.72929216e-01 -1.91511948e+00  9.19301364e-01
  1.68704106e+00  3.39941381e+00 -1.31357417e+00 -1.55955084e+00
  5.26289421e-01  5.10066569e-01  9.21489466e-01 -5.29070614e-02
  1.32846540e+00  3.66834438e+00 -1.21586370e+00 -3.17341804e-01
  1.49462972e+00 -1.11932421e+00  1.60012728e+00  8.02210737e-02
  1.91722116e+00  9.52929461e-01 -6.

<font color='red'>NB: Once you redefine your random variables using X.rvs(N), you must rerun the earlier code to run this cell again. </font> 

##### Turn to estimation



So, we now have data on *realizations* $(y,X)$ which take the
     Now forget that we know $\beta$ and let&rsquo;s estimate it, using
     OLS.  As a numerical matter it&rsquo;s better to avoid explicitly
     inverting the $(X^T X)$ matrix; instead we can solve the &ldquo;normal&rdquo;
     equations.



##### Numerical solution



In [10]:
# 1.3. ORIGINAL CODE

from scipy.linalg import inv, sqrtm

b = np.linalg.solve(X.T@X,X.T@y)

e = y - X@b

vb = e.var()*inv(X.T@X)

print(b,end='\n\n')
print(sqrtm(vb))

[0.54382267 0.99563508]

[[ 0.01469681 -0.00224287]
 [-0.00224287  0.01048138]]


<font color='red'> *notes*: </font>
- `X.T` produces the transpose of X; R::t(X)
- `np.linalg.solve(a, b)` "Solve a linear matrix equation, or system of linear scalar equations.  Computes the "exact" solution, `x`, of the well-determined, i.e., full rank, linear matrix equation `ax = b`."
- `print(x, end = '\n\n')` by default `end = '\n'` in the `print()` function, which starts a new line.  However, when `'\n\n'` is instead entered, your notebook will also skip a line between the printed information and the next output.  To avoid a new line being started, you can instead enter `' '`. 
- `inv( )` is a function that calculates the inverse of a matrix
- `sqrtm( )` is the matrix square root function.

In [48]:
# 1.3. CODE ABOVE WITH COMMENTS AND PRINTING

# import both the 'inv' and 'sqrtm' functions from the 'linalg' functions of the SciPy module
from scipy.linalg import inv, sqrtm

# solve for b in the equation X.T@X@b = X.T@y    b = solve(t(X) %*% X) %*% t(X) %*% y
b = np.linalg.solve(X.T@X,X.T@y)
print("b =", b)

# e gets R:: y - X %*% b 
e = y - X@b
print("e =", e)

# An additional line simply to show what e.var() generates
evar = e.var()
print("evar =", evar)

# vb gets R:: var(e) * solve(t(X) %*% X)
vb = e.var()*inv(X.T@X)
print("vb =", vb)

# print b with an additional line after the results
print(b,end='\n\n')

# print the squareroot of the matrix vb
print(sqrtm(vb))

b = [0.48733973 1.02314017]
e = [-1.06136115e-01 -1.04244294e-01 -8.22962158e-01  6.57504296e-01
 -5.67355626e-01 -4.62722401e-01  2.05093577e-02 -4.64945246e-01
 -6.11217441e-01  4.58831214e-01  1.90567791e-01 -6.22041208e-01
 -1.16449535e-01  3.45170038e-01  3.84591212e-01  1.54259448e-01
 -1.73285633e+00 -6.26650267e-02  1.13202485e-01 -2.55643315e-01
 -5.30006309e-01  5.59453518e-01  1.02996082e+00 -1.34219894e-01
  1.33686592e-01  3.97901761e-01  9.79020187e-01 -7.00798286e-02
 -4.23323950e-01  1.48368520e-01 -3.11763267e-01 -3.28342031e-01
 -5.32310056e-01  5.93463516e-02  4.59391819e-01 -3.92615132e-01
 -3.74088948e-01  8.07584341e-01  3.07646186e-01 -4.31417749e-01
  4.03795391e-01  1.51158413e-01 -6.29627863e-01 -2.90045814e-01
  1.10314948e+00  1.78976864e-02  4.00047489e-01 -5.94328747e-02
  3.03915261e-01 -8.48278140e-02  1.69690710e-01 -3.50864990e-01
 -3.13058835e-01  7.19253132e-01  2.76768462e-01 -4.38702552e-01
 -7.25856224e-01 -1.20984160e-02  6.56840849e-01  7.474826

### 2. [Weighted Regression in =python=](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Materials/weighted_regression.ipynb)



or see [weighted_regressions on github](https://github.com/ligonteaching/ARE212_Materials/blob/master/weighted_regression.ipynb)

The fact that $T$ and $u$ are &ldquo;independent&rdquo; (or at least
orthogonal) variables means that if we want to compute a
&ldquo;classical&rdquo; regression we&rsquo;d do it something like this:



##### Define independent random variables



In [54]:
# 2.1. ORIGINAL CODE

%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal

k = 3 # Number of observables in T

mu = [0]*k
Sigma=[[1,0.5,0],
       [0.5,2,0],
       [0,0,3]]

T = multivariate_normal(mu,Sigma)

u = multivariate_normal(cov=0.2)

<font color='red'> *notes*: </font>
- `len(x)` returns the length of an array; R::length(x)
- `np.shape(x)` returns the dimensions of a matrix; R::dim(x)

In [58]:
# 2.1. CODE ABOVE WITH COMMENTS AND PRINTING

%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal

k = 3 # Number of observables in T
print("k =", k)

mu = [0]*k
print("mu =", mu)
print("Length mu =", len(mu))


Sigma=[[1,0.5,0],
       [0.5,2,0],
       [0,0,3]]
print("Sigma =", Sigma)
print("Shape Sigma =", np.shape(Sigma))

T = multivariate_normal(mu,Sigma)
print("T =", T)

u = multivariate_normal(cov=0.2)
print("u =", u)

k = 3
mu = [0, 0, 0]
Length mu = 3
Sigma = [[1, 0.5, 0], [0.5, 2, 0], [0, 0, 3]]
Shape Sigma = (3, 3)
T = <scipy.stats._multivariate.multivariate_normal_frozen object at 0x7f716d6ba2b0>
u = <scipy.stats._multivariate.multivariate_normal_frozen object at 0x7f7121f5b278>


##### Define =X=



Recall that $X$ can depend on $T$ and $u$.  This dependence needn&rsquo;t be
linear!  For example, suppose $X=T^3D + u$, where $D$ is an
$\ell\times k$ matrix.



##### Construct Sample



To construct a sample of observables $(y,X,T)$ we just use the regression equation,
      plus an assumption about the value of $\beta$:



In [56]:
# 2.2. ORIGINAL CODE

beta = [1/2,1]

D = np.random.random(size=(3,2)) # Generate random 3x2 matrix

N=1000 # Sample size

# Now: Transform rvs into a sample
T = T.rvs(N)

u = u.rvs(N) # Replace u with a sample

X = (T**3)@D  # Note use of ** operator for exponentiation

y = X@beta + u # Note use of @ operator for matrix multiplication

<font color='red'>NB: Once you redefine your random variables using X.rvs(N), you must rerun the earlier code to run this cell again. </font> 

<font color='red'> *notes*: </font>
- `**` for exponents so that `3**2` = $3^2$; R::3^2 or 3**2 (i.e. the same)

In [59]:
# 2.2. CODE ABOVE WITH COMMENTS AND PRINTING

beta = [1/2,1]
print("beta =", beta)
print("Length beta =", len(beta))

D = np.random.random(size=(3,2)) # Generate random 3x2 matrix
print("D =", D)
print("Shape D =", np.shape(D))

N=1000 # Sample size

# Now: Transform rvs into a sample
T = T.rvs(N)
print("T =", T)
print("Shape T =", np.shape(T))

u = u.rvs(N) # Replace u with a sample
print("u =", u)
print("Shape u =", np.shape(u))
print("Length u =", len(u))

X = (T**3)@D  # Note use of ** operator for exponentiation
print("Shape X =", np.shape(X))

y = X@beta + u # Note use of @ operator for matrix multiplication
print("Shape y =", np.shape(y))

beta = [0.5, 1]
Length beta = 2
D = [[0.9747384  0.00637538]
 [0.88560785 0.13854454]
 [0.94139493 0.28054936]]
Shape D = (3, 2)
T = [[ 1.79044788  1.57618282 -0.62527475]
 [ 0.95042714  1.37823013  1.46242992]
 [-1.22589168 -0.09118055 -0.18603817]
 ...
 [ 1.73295916 -0.43395036  0.91862477]
 [-0.50308082 -0.42424176  1.46060027]
 [ 0.1561883  -0.04889125 -1.52390502]]
Shape T = (1000, 3)
u = [ 4.10811167e-01 -4.71750893e-01 -3.81919493e-01  6.03697253e-02
 -4.13359733e-01 -2.42025650e-01 -8.70931439e-01  3.20978893e-01
 -1.76539975e-01  2.40444144e-01  7.33148208e-02 -4.06563731e-01
  2.94791934e-02  1.76831242e-01  1.00869048e-03 -4.86030867e-02
  2.02104019e-01  5.48479850e-01  1.19939424e-01 -2.61510235e-01
 -8.70381677e-02 -2.56647666e-01 -4.00420040e-01 -8.63562599e-02
  4.05892979e-02  1.39330094e-01  2.92040681e-01 -4.47211305e-01
  1.44864243e-01  2.51371139e-01 -4.07993098e-01 -6.55088144e-02
  9.61217714e-02  3.68555876e-01  7.57784744e-01 -3.48685909e-01
 -2.68729141e-01  

##### Turn to estimation



So, we now have data on *realizations* $(y,X,T)$.  Now forget
     that we know $\beta$ and let&rsquo;s estimate it, using weighted least
     squares.  As a numerical matter it&rsquo;s better to avoid explicitly
     inverting the $(T^T X)$ matrix; instead we can solve the &ldquo;normal&rdquo;
     equations

\begin{align*}
   X'y &= X' X b + X' u\\
   \mbox{E}(T'u) = 0
\end{align*}



##### Numerical solution



In the classical case we were trying to solve a linear system that
 took the form $Ab=0$, with $A$ a square matrix.  In the present case
 we&rsquo;re also trying to solve a linear system, but with a matrix $A$
 that may have more rows than columns.  Provided the rows are linearly
 independent, this implies that we have an **overidentified** system of
 equations.  We&rsquo;ll return to the implications of this later, but for
 now this also calls for a different numerical approach, using
 `np.linalg.lstsq` instead of `np.linalg.solve`.



In [53]:
# 2.3. ORIGINAL CODE

from scipy.linalg import inv, sqrtm

b = np.linalg.lstsq(T.T@X,T.T@y)[0] # lstsqs returns several results

e = y - X@b

print(b)

TXplus = np.linalg.pinv(T.T@X) # Moore-Penrose pseudo-inverse

# Covariance matrix of b
vb = e.var()*TXplus@T.T@T@TXplus.T  # u is known to be homoskedastic

print(vb)

[0.50661294 0.99862493]
[[ 4.04318742e-05 -1.99102565e-05]
 [-1.99102565e-05  1.05915628e-05]]


/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """


In [17]:
# np.linalg.lstsq?
# Return the least-squares solution to a linear matrix equation.
## Solves the equation `a x = b` by computing a vector `x` that
## minimizes the Euclidean 2-norm `|| b - a x ||^2`.  The equation may
## be under-, well-, or over- determined (i.e., the number of
## linearly independent rows of `a` can be less than, equal to, or
## greater than its number of linearly independent columns).  If `a`
## is square and of full rank, then `x` (but for round-off error) is
## the "exact" solution of the equation.

In [18]:
# np.linalg.pinv?
# Compute the (Moore-Penrose) pseudo-inverse of a matrix.
## Calculate the generalized inverse of a matrix using its
## singular-value decomposition (SVD) and including all
## *large* singular values.

In [60]:
# 2.3. CODE ABOVE WITH COMMENTS AND PRINTING

# import both the 'inv' and 'sqrtm' functions from the 'linalg' functions of the SciPy module
from scipy.linalg import inv, sqrtm

# solve for b in the equation T.T@X@b = T.T@y
b = np.linalg.lstsq(T.T@X,T.T@y, rcond=-1)[0] # lstsqs returns several results
# note that I'm also passing it rcond=-1 to mute the error above and maintain the old parameter

# e gets R:: y - X %*% b 
e = y - X@b
print

print("b =", b)

# calculate the Moore-Penrose pseudo-inverse
TXplus = np.linalg.pinv(T.T@X) # Moore-Penrose pseudo-inverse

# Covariance matrix of b
## vb gets var(e) * TXplus %*% t(T) %*% T %*% t(TXplus)
vb = e.var()*TXplus@T.T@T@TXplus.T  # u is known to be homoskedastic

print("vb =",vb)

b = [0.49651782 1.01160452]
vb = [[ 6.94188425e-06 -2.61030984e-05]
 [-2.61030984e-05  1.08902749e-04]]


### Final Word

This discussion section originally covered [random_variables0](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Materials/random_variables0.ipynb), but the related notes have been moved to and expanded in [\[ARE 212\] Discussion Section - Python 03](https://datahub.berkeley.edu/user/benjaminkrause/notebooks/ARE212_Discussion_Section/%5BARE%20212%5D%20Discussion%20Section%20-%20Python%2003.ipynb)